Add make link config to root

diff --git a/client/Makefile b/client/Makefile
--- a/client/Makefile
+++ b/client/Makefile
@@ -8,4 +8,10 @@ yarn:
 		(cd $$dir && yarn) || (echo "Failed to yarn $$dir"; exit 1); \
 	done
 
+link:
+	@for dir in $(WEB_SUBDIRS); do \
+		echo "---Linking $$dir---"; \
+		(cd $$dir && yarn link @cortezaproject/corteza-js && yarn link @cortezaproject/corteza-vue) || (echo "Failed to link $$dir"; exit 1); \
+	done
+
 .DEFAULT_GOAL := yarn
